---

apiVersion: v1
kind: Namespace
metadata:
  name: snake

---

apiVersion: v1
kind: Service
metadata:
  name: snake-service
  namespace: snake
spec:
  selector:
    app: snake-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-deployment
  namespace: snake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-app
  template:
    metadata:
      labels:
        app: snake-app
    spec:
      containers:
        - name: snake
          image: aramirol/snake:latest
          ports:
            - containerPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-ingress
  namespace: snake
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/secure-backends: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: snake.casare.int
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: snake-service
            port:
              number: 8000
